# Generated by Django 5.1.5 on 2025-01-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_employee_task_assigned_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_emp',
            new_name='assigned_to',
        ),
    ]
